import type { Metadata } from "next";
import "tailwindcss/tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-green-700">{children}</body>
    </html>
  );
}
